In [11]:
import numpy as np

NUMPY INDEXING AND SLICING OF VECTORS

In [12]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[6]

np.int64(17)

In [14]:
arr_slice = arr[1:5:1]
arr_slice

array([12, 13, 14, 15])

In [17]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [18]:
arr[5]

array([26, 27, 28, 29, 30])

Indexing

In [23]:
arr[5,4]

np.int64(30)

SLICING

In [24]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [29]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [30]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

BOOLEAN INDEXING

In [31]:
arr =  np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [33]:
bool_index=  arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [34]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])