In [3]:
import numpy as np

Arthematic Operataion

In [ ]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [ ]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [ ]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [ ]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [ ]:
a1 // a2

array([0, 0, 0, 0, 0])

BroadCasting

In [ ]:
l = [1,2,3,4,5]
arr = np.array(l)

In [ ]:
arr + 10

array([11, 12, 13, 14, 15])

In [4]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [5]:
arr2 + 10


array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

Deep And shallow Copy

In [6]:
a = np.arange(1,20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [12]:
slice = a[:5]
slice = slice + 10
slice

array([11, 12, 13, 14, 15])

In [13]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

Concept of shallow copy nothing changed

In [23]:
a
b = a.copy()

In [24]:
b[0] = 99

In [25]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [26]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

Matrix Operation

In [28]:
A = np.array([[1, 2], [3,4]])
B = np.array([[5, 6], [7, 8]])

In [29]:
A

array([[1, 2],
       [3, 4]])

In [30]:
B

array([[5, 6],
       [7, 8]])

In [31]:
A @ B

array([[19, 22],
       [43, 50]])

Transpose

In [32]:
A.T

array([[1, 3],
       [2, 4]])

ADVANCE ARRAY MANIPULATION

Array Stacking

In [35]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [36]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting Array

In [42]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [47]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]