In [48]:
import numpy as np

**Valid Sudoku**

In [49]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [50]:
# check sum in rows
b = np.sum(s,axis= 1)
for i in b:
  if i != 45:
    print('sudoku is invalid')
    break
else:
    print('sudoku is valid in rows')

sudoku is valid in rows


In [51]:
# Check sum in column
c = np.sum(s, axis= 0)
for i in c:
  if i != 45:
    print('sudoku is invalid')
    break
else:
    print('sudoku is valid in column')

sudoku is valid in column


In [52]:
d=np.sum(s[0:3,0:3])
d


np.int64(45)

In [53]:
if np.sum(d) == 45:
    print('sudoku is valid in 3*3')
else:
    print('sudoku is invalid')

sudoku is valid in 3*3


In [54]:
# Check sum of all 9 blocks
for i in range(0,9,3):
  for j in range(0,9,3):
    n=s[i:i+3,j:j+3]
    print(n.sum())
    if n.sum() != 45:
      print('sudoku is invalid')
      break
else:
  print('sudoku is valid')

45
45
45
45
45
45
45
45
45
sudoku is valid


**General Questions**

In [55]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [56]:
#Get the shape of the matrix.
data.shape



(5, 3)

In [57]:
#Find the average age of students.
avg= np.mean(data[:,0])
avg


np.float64(18.4)

In [58]:
#Extract Math marks of all students.
math= data[:,1]
math


array([85, 92, 76, 65, 90])

In [59]:
#Find the highest Science mark.
hig=  np.max(data[:,2])
hig





np.int64(95)

In [60]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]> 90]

array([[19, 92, 88]])

In [61]:
#Increase Math marks of all students by 5.
inc= data[:,1] + 5
inc


array([90, 97, 81, 70, 95])

In [62]:
#Find how many students are younger than 19.
len(data[data[:,0] < 19])


3

In [63]:

#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

In [68]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])

In [69]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [66]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])