In [ ]:
import numpy as np

Basic array creation

In [ ]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [ ]:
a = [1 , 3, 4.4, 5 ,'hello']
a

[1, 3, 4.4, 5, 'hello']

In [ ]:
np.array(a)

array(['1', '3', '4.4', '5', 'hello'], dtype='<U32')

Vector and matrice

In [ ]:
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array generation function

Range Function

In [ ]:
arr = np.arange(1, 11, 2)
arr


array([1, 3, 5, 7, 9])

genartion with some zero

In [ ]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

Ones function

In [ ]:
arr = np.ones((2,2))
arr

array([[1., 1.],
       [1., 1.]])

Linsspace ( Linear space)

In [ ]:
arr = np.linspace(0,1,50)
arr

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

Random generation function

In [ ]:
np.random.rand(5)

array([0.38409004, 0.66849534, 0.42190115, 0.82000933, 0.02225731])

In [ ]:
np.random.randn(10)

array([ 1.98274035, -1.12022431,  1.2473514 , -0.29797565,  2.16148761,
        0.89678533, -0.00687478,  0.33567535,  1.0357662 ,  0.47180692])

In [ ]:
np.random.randint(10,20,10)

array([19, 16, 13, 11, 19, 16, 17, 17, 18, 18])

Array Attributes

In [ ]:
arr =np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

Array Methods

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [ ]:
arr.mean()

np.float64(5.0)

In [ ]:
arr.std()

np.float64(2.581988897471611)

In [ ]:
arr.argmax()

np.int64(8)

In [ ]:
arr.argmin()

np.int64(0)

Reshaping And Resizing

In [ ]:
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])